name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.7
        uses: actions/setup-java@v1
        with:
          java-version: 1.7
      - name: Build
        run: ant -noinput compile
      - name: Test
        run: ant -noinput test

